<?php

/**
 * Implement  	hook_user_login(&$edit, $account); for redirect login user to profile page.
 */

function custom_sso_attributes_user_login(&$edit, $account) {
	if($_REQUEST['form_id'] == 'user_login_block' || $_REQUEST['form_id'] == 'user_login') {
      global $user;
      $prof = profile2_by_uid_load($user->uid, 'main');
      //print_r($prof->pid);die();
      if(!empty($prof->pid)) {
      	$_GET['destination'] = '<front>';
      }
      else {
      	$_GET['destination'] = 'user/'.$user->uid.'/edit/main';
      	//drupal_goto('<front>');
      }
      
	}
	
}

