<?php
/**
 * @file
 * Code for the PLAY Library Program feature.
 */

include_once 'play_library_program.features.inc';

/**
 * Implements hook_field_widget_form_alter().
 */
function play_library_program_field_widget_form_alter(&$element, &$form_state, $context) {
  if (isset($element['value']['#field_name']) && $element['value']['#field_name'] == 'field_activity_fired_hook') {
    $options = array(
      '' => t('- Select Firing Hook -'),
      'user_insert' => t('User just registered'),
      'user_login' => t('User logged in for first time'),
    );
    $entities = entity_get_info();
    foreach($entities as $entity_key => $entity) {
      if ($entity_key == 'node') {
        $entity['module'] = 'node';
      }
      if (isset($entity['module']) && ($entity['module'] == 'eck' || $entity['module'] == 'node')) {
        foreach ($entity['bundles'] as $bundle_key => $bundle_options) {
          $options["entity_insert|{$entity['module']}|{$bundle_key}"] = t("Insert new @bundle", array('@bundle' => $bundle_options['label']));
        }
      }
    }
    $element['value']['#type'] = 'select';
    $element['value']['#options'] = $options;
    $element['value']['#size'] = 0;
  }
}

/**
 * Implements hook_user_insert()
 */
function play_library_program_user_insert(&$edit, $account, $category) {
  $query = new EntityFieldQuery();
  $query->addCondition('entity_type', 'activity');
  $query->addCondition('bundle', 'activity');
  $query->fieldCondition('field_activity_fired_hook', 'value', 'user_insert');
  $result = $query->execute();
  dpm($result);
}