<?php
/**
 * @file
 * Code for the PLAY Library Program feature.
 */

include_once 'play_library_program.features.inc';

/**
 * Implements hook_field_widget_form_alter().
 */
function play_library_program_field_widget_form_alter(&$element, &$form_state, $context) {
  if (isset($element['value']['#field_name']) && $element['value']['#field_name'] == 'field_activity_fired_hook') {
    $options = array(
      '' => t('- Select Firing Hook -'),
      'user_insert' => t('User just registered'),
    );
    // For now, only deal with nodes and other ECK content models.
    $entities = entity_get_info();
    foreach($entities as $entity_key => $entity) {
      if ($entity_key == 'node') {
        $entity['module'] = 'node';
      }
      if (isset($entity['module']) && ($entity['module'] == 'eck' || $entity['module'] == 'node')) {
        foreach ($entity['bundles'] as $bundle_key => $bundle_options) {
          $options["entity_insert|{$entity_key}|{$bundle_key}"] = t("Insert new @bundle", array('@bundle' => $bundle_options['label']));
        }
      }
    }
    $element['value']['#type'] = 'select';
    $element['value']['#options'] = $options;
    $element['value']['#size'] = 0;
  }
}

/**
 * Implements hook_user_insert().
 */
function play_library_program_user_insert(&$edit, $account, $category) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'activity');
  $query->entityCondition('bundle', 'activity');
  $query->fieldCondition('field_activity_fired_hook', 'value', 'user_insert');
  $result = $query->execute();
  foreach ($result as $entity_key => $entity_values) {
    if ($entity_key == 'activity') {
      foreach ($entity_values as $entity) {
        play_library_program_create_activity_entry($entity->id, $account->uid);
      }
    }
  }
}

/**
 * Implements hook_entity_insert().
 */
function play_library_program_entity_insert($entity, $type) {
  // Could be node, could be eck, could be something else, but easy to check.
  if (!isset($entity->type)) {
    return;
  }
  // Also hardcoding that we do not create *new* activity entries for an
  // activity entry.
  if ($entity->type !== 'activity_entry') {
    _play_library_program_invoke_activity_entry_hooks($entity, $type);
  }
  if ($entity->type == 'activity_entry') {
    // Start figure out which activity is associated with entry.
    $activity_id = $entity->field_activity_entry_activity[LANGUAGE_NONE][0]['target_id'];
    $activities = entity_load('activity', array($activity_id));
    $activity = reset($activities);
    $points = intval($activity->field_activity_points[LANGUAGE_NONE][0]['value']);
    $current_participation_count = play_library_program_retrieve_activity_participation($activity_id, $entity->uid);
    if ($points > 0 && $current_participation_count <= $activity->field_activity_limit[LANGUAGE_NONE][0]['value']) {
      $userpoints_txn = array(
        'uid' => $entity->uid,
        'points' => $points,
      );
      userpoints_userpointsapi($userpoints_txn);
    }
  }
}

/**
 * Implements hook_userpoints().
 */
function play_library_program_userpoints($op, &$params = array()) {
  if ($op == 'points after') {
    $user_points = userpoints_get_current_points($params['uid']);
    $user_pre_points = $user_points - $params['points'];
    $tier_rewards = _play_library_program_get_tier_reward_ids($user_pre_points, $user_points);
    foreach ($tier_rewards as $rid) {
      play_library_program_create_reward_claim($rid, $params['uid']);
    }
    // Check global rewards
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'activity');
    $query->entityCondition('bundle', 'activity');
  }
}

/**
 * Retrieves how many times an activity has been performed.
 */
function play_library_program_retrieve_activity_participation($activity_id, $account_id) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'activity');
  $query->entityCondition('bundle', 'activity_entry');
  $query->propertyCondition('uid', $account_id);
  $query->fieldCondition('field_activity_entry_activity', 'target_id', $activity_id);
  return $query->count()->execute();
}

/**
 * Creates a new activity entry
 */
function play_library_program_create_activity_entry($activity_id, $account_id) {
  $activities = entity_load('activity', array($activity_id));
  $activity = reset($activities);
  $title = t("@activity on @time", array('@activity' => $activity->title, '@time' => date('Y-m-d H:i')));
  $activity_entry = entity_create('activity', array('type' => 'activity_entry', 'title' => $title, 'uid' => $account_id));
  $activity_entry->field_activity_entry_activity[LANGUAGE_NONE][0]['target_id'] = $activity->id;
  entity_save('activity', $activity_entry);
}

/**
 * Creates a new activity entry
 */
function play_library_program_create_reward_claim($reward_id, $account_id) {
  $rewards = entity_load('reward', array($reward_id));
  $reward = reset($rewards);
  $title = t("@reward on @time", array('@reward' => $reward->title, '@time' => date('Y-m-d H:i')));
  $reward_claim = entity_create('reward', array('type' => 'reward_claim', 'title' => $title, 'uid' => $account_id));
  $reward_claim->field_reward_claim_id[LANGUAGE_NONE][0]['target_id'] = $reward->id;
  entity_save('activity', $reward_claim);
}

/**
 * Retrieves how many times an activity has been performed.
 */
function _play_library_program_get_tier_reward_ids($user_pre_points, $user_points) {
  $rids = array();
  // Get the non-repeated rewards first.
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'reward');
  $query->entityCondition('bundle', 'point_driven_reward');
  $query->fieldCondition('field_pdr_point_marker', 'value', $user_pre_points, '>');
  $query->fieldCondition('field_pdr_point_marker', 'value', $user_points, '<=');
  $query->fieldCondition('field_pdr_point_repeatable', 'value', 0);
  $results = $query->execute();
  if (!empty($results['reward'])) {
    foreach($results['reward'] as $reward) {
      $reward_entities = entity_load('reward', array($reward->id));
      $reward_entity = reset($reward_entities);
      $rids[] = $reward_entity->field_pdr_point_reward[LANGUAGE_NONE][0]['target_id'];
    }
  }

  // Process the repeated ones next.
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'reward');
  $query->entityCondition('bundle', 'point_driven_reward');
  $query->fieldCondition('field_pdr_point_repeatable', 'value', 1);
  $results = $query->execute();
  if (!empty($results['reward'])) {
    foreach($results['reward'] as $reward) {
      $reward_entities = entity_load('reward', array($reward->id));
      $reward_entity = reset($reward_entities);
      $modulus = $reward_entity->field_pdr_point_marker[LANGUAGE_NONE][0]['value'];
      for ($i = $user_points; $i > $user_pre_points; $i--) {
        if ($i % $modulus == 0) {
          $rids[] = $reward_entity->field_pdr_point_reward[LANGUAGE_NONE][0]['target_id'];
        }
      }
    }
  }

  return $rids;
}

/**
 * Performs general firing hook check to create new activity entries
 */
function _play_library_program_invoke_activity_entry_hooks($entity, $type) {
  $hook = "entity_insert|{$type}|{$entity->type}";
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'activity');
  $query->entityCondition('bundle', 'activity');
  $query->fieldCondition('field_activity_fired_hook', 'value', $hook);
  $result = $query->execute();
  foreach ($result as $entity_key => $entity_values) {
    if ($entity_key == 'activity') {
      foreach ($entity_values as $activity_entity) {
        $account = user_load($entity->uid);
        play_library_program_create_activity_entry($activity_entity->id, $account->uid);
      }
    }
  }
}