<?php

/**
 * Implements hook_form_alter().
 */
function payl_program_customizations_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_register_form') {
    $setting = array(
      'payl_program_customizations_birthday_limit' => strtotime('-13 years'),
    );
    drupal_add_js($setting, array('type' => 'setting'));
    drupal_add_js(drupal_get_path('module', 'payl_program_customizations') . '/payl_program_customizations.js');
    $form['current_username'] = array(
      '#markup' => '<h3 class="username">Username: <span class="current-username"></span></h3>',
      '#weight' => 1,
    );
    $form['#validate'][] = 'payl_program_customizations_user_register_validate';
    if (!empty($form['profile_main'])) {
      $form['profile_main']['field_user_address'][LANGUAGE_NONE][0]['name_block'] = array(
        '#type' => 'value',
        '#value' => 'User address',
      );
      $form['profile_main']['field_user_address'][LANGUAGE_NONE][0]['organisation_block'] = array(
        '#type' => 'value',
        '#value' => '',
      );
    }
  }
}

function payl_program_customizations_user_register_validate($form, &$form_state) {
  $values = $form_state['values'];
  if (empty($values['name'])) {
    form_set_error('name', t('Please ensure to create your own username OR generate a new username'));
  }
}
