<?php

/**
 * Implements hook_init().
 */
function program_configuration_init() {
  $program_start_date = variable_get('pmc_start_date', 0);
  $program_end_date = variable_get('pmc_end_date', 0);
  $setting = array('library_custom' => array('proStart' => $program_start_date, 'proEnd' => $program_end_date));
  drupal_add_js($setting, 'setting');
}

/**
 * Implementation of hook_menu()
 */
function program_configuration_menu(){
	
  // Adding link for setting purchase link for booklist
  $items['admin/config/system/program_configuration'] = array(
	  'title' => 'Program Configuration',
	  'description' => 'Program configuration page.',
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('program_configuration_purchase_link'),
	  'access arguments' => array('access administration pages'),
	  'type' => MENU_NORMAL_ITEM,
	  'file' => 'inc/platform_details.inc',
	  // 'file path' => drupal_get_path('module', 'library_custom'),
  );
}


/**
 * Implements function to check if program is active or not.
 *
 * @return Boolean
 *   0 if not active, 1 if active 
 */

function is_program_active() {
  $program_start_date = variable_get('pmc_start_date', 0);
  $program_end_date = variable_get('pmc_end_date', 0);
  if ($program_start_date && $program_end_date) {
	$now = time();
	$program_start_date = strtotime($program_start_date);
	$program_end_date = strtotime($program_end_date);

	if (($now >= $program_start_date) && ($now <= $program_end_date)) {
	  return 1;
	} else {
	  drupal_set_message("The program is currently closed.");
	  return 0;
	}
  }
  return 1;
}
