<?php
/**
 * @file
 * A module for private message in dashboard
 *
 * This module provides a block that displays
 * the recent message on patron dashboard.
 */

/**
 * Implementation of hook_menu()
 */
function private_msg_custom_menu() {
  $items['my-reviews'] = array(
    'title' => 'Reviews',
    'page callback' => 'user_reviews',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['my-booklist'] = array(
    'title' => 'Booklist',
    'page callback' => 'user_booklist',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  // Adding link for setting purchase link for booklist
  $items['admin/config/system/platform_configuration'] = array(
	  'title' => 'Platform Configuration',
	  'description' => 'Chilco platform configuration page.',
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('platform_configuration_purchase_link'),
	  'access arguments' => array('access administration pages'),
	  'type' => MENU_NORMAL_ITEM,
	  'file' => 'inc/platform_configuration_purchase_link.inc',
	  'file path' => drupal_get_path('module', 'private_msg_custom'),
  );

   $items['profile_avatar'] = array(
	  'title' => 'Profile Avatar',
	  'description' => 'providing tabs for different avatars',
	  'page callback' => 'drupal_get_form',
    'page arguments' => array('ajax_avatar_profile_checkboxes'),
	  'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
	  'file' => 'inc/platform_configuration_purchase_link.inc',
	  'file path' => drupal_get_path('module', 'private_msg_custom'),
  );

  return $items;
}

/**
 * Implements function to check if program is active or not.
 *
 * @return Boolean
 *   0 if not active, 1 if active 
 */
function is_program_active() {
  $program_start_date = variable_get('pmc_start_date', 0);
  $program_end_date = variable_get('pmc_end_date', 0);
  if ($program_start_date && $program_end_date) {
    $now = time();
    $program_start_date = strtotime($program_start_date);
    $program_end_date = strtotime($program_end_date);

    if (($now >= $program_start_date) && ($now <= $program_end_date)) {
      return 1;
    } else {
      drupal_set_message("The program is currently closed.");
      return 0;
    }
  }
  return 1;
}

function private_msg_custom_init() {
  $program_start_date = variable_get('pmc_start_date', 0);
  $program_end_date = variable_get('pmc_end_date', 0);
  $setting = array('private_msg_custom' => array('proStart' => $program_start_date, 'proEnd' => $program_end_date));
  drupal_add_js($setting, 'setting');
  
}


/**
 * Implementation of hook_form_profile2_edif_PROFILE_NAME_form_alter()
 */
function private_msg_custom_form_profile2_edit_main_form_alter(&$form, $form_state) {

	$form['profile_main']['field_user_avatar'] = array('#attributes' => array('style' => 'display:none'));

  $query = db_select('field_data_field_avatar_type','type');
	$query->fields('type',array('field_avatar_type_tid','entity_id'));
	$query->join('eck_user_avatar','eck','eck.id = type.entity_id');
	$query->join('taxonomy_term_data','tax','tax.tid = type.field_avatar_type_tid');
	$query->fields('tax',array('name'));
  $query->fields('eck',array('title'));
	$query_avatar = $query->execute()->fetchAll();

	foreach ($query_avatar as $key => $value) {
    $tax_name[$value->field_avatar_type_tid] = $value->name;
    $avatar_name[$value->field_avatar_type_tid][] = $value->entity_id;
  }

  $num_avatar = !empty($form_state['values']['avatar_select']) ? $form_state['values']['avatar_select'] : 1;
  $none_array = array(0 => '-None-');
  $array2 = $none_array + $tax_name;

  $form['avatar_select'] = array(
    '#title' => t('Select your user avatar?'),
    '#type' => 'select',
    '#options' => $array2,
    '#ajax' => array(
      'callback' => 'ajax_autocheckboxes_callback_avatar',
      'wrapper' => 'checkboxes-div',
      'effect' => 'slide',
      'progress' => array('type' => 'none'),
    ),
    //'#weight' => 5,
  );

  $form['checkboxes_fieldset'] = array(
    '#title' => t("Avatars"),
    '#prefix' => '<div id="checkboxes-div">',
    '#suffix' => '</div>',
    '#type' => 'fieldset',
    //'#weight' => 5,
  );

	foreach ($avatar_name[$num_avatar] as $key => $value) {
		$form['checkboxes_fieldset']["avatar_checkbox-$value"] = array(
	    '#type' => 'checkbox',
	    '#title' => avatar_images_list($value),
	    '#prefix' => '<div class="$value">',
	    '#suffix' => '</div>',
	    '#attributes' => array(
	        'class' => array(
	          'user_avatar'
	        ),
	     ),
  	);
	}

	array_unshift($form['#submit'], 'submit_for_avatar');
}

function avatar_images_list($value) {
  $query = db_select('field_data_field_avatar_image', 't');
  $query->join('file_managed', 'n', 'n.fid = t.field_avatar_image_fid');
  $result = $query
    ->fields('n', array('uri'))
    ->condition('t.entity_id', $value)
    ->execute();
    $img_uri = $result->fetchObject();
    $img_uri = $img_uri->uri;
    $style = 'avatar_style';
    $img_path = image_style_url($style, $img_uri);
    $img = "<img src='$img_path'>";
  return $img;
}


function ajax_autocheckboxes_callback_avatar($form, $form_state) {
  return $form['checkboxes_fieldset'];
}

// submit handler for create user account form.
function submit_for_avatar($form, $form_state) {
  foreach ($form_state['values'] as $key => $value) {
  	if($value == 1){
		  $avatar_entity = 'avatar_checkbox-';
	    $av_entity_id = strpos($key, $avatar_entity);

	    if ($av_entity_id !== false) {
	      // use sesion to pass avatar ID to profile presave hook.
	      $_SESSION['user_avatar_id'] = substr($key, 16);
	      break;
	    }
	  }
	}
}

/**
 * Implementation of hook_profile2_presave()
 */
function private_msg_custom_profile2_presave($profile) {

	if (isset($_SESSION['user_avatar_id'])){
	  $profile->field_user_avatar[LANGUAGE_NONE][0]['target_id'] = $_SESSION['user_avatar_id'];
	  unset($_SESSION['user_avatar_id']);
	}
}

/**
 * Implementation of hook_form_alter()
 */
function private_msg_custom_form_alter(&$form, &$form_state, $form_id) {

  if($form_id == 'review_book_node_form') {
    drupal_set_title('Write a Book Review');
  }

  if($form_id == 'user_register_form') {
  }

  if($form_id == 'booklist_node_form') {
    drupal_set_title('Create a Booklist');
  }

  if($form_id == 'review_activity_node_form') {
    drupal_set_title('Write an Activity Review');
  }

  // Adding purchase link for booklist
	if($form_id == 'booklist_node_form') {
		$form['purchase_link'] = array(
		  '#type' => 'link',
		  '#title' => 'Suggest a purchase',
		  '#href' => variable_get('pmc_purchase_link'),
		  '#attributes' => array('target' => '_blank'),
		  '#weight' => 3,
		);

		return $form;
	}
}

function user_reviews() {
	return '';
}

function user_booklist() {
  return '';
}

/**
 * Implements hook_block_info().
 */
function private_msg_custom_block_info() {
  $blocks = array();
  $blocks['pm_block'] = array(
    'info' => t('Private Message Dashboard Block'),
  );

  $blocks['homepage_slider'] = array(
    'info' => t('Homepage booklist slider Block'),
  );

  $blocks['menu_for_mobile'] = array(
    'info' => t('Menu block for mobile'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function private_msg_custom_block_view($delta = '') {
  $block = array();
  
  switch($delta) {
    case 'pm_block' :
      $block['content'] = pm_block_view();
      break;

    case 'homepage_slider' :
      $block['content'] = homepage_slider();
      break;

    case 'menu_for_mobile' :
      $block['content'] = header_menu_mobile();
      break;
  }
  
  return $block;
}

/**
 * Function callback for private_msg_custom_block_view.
 */
function pm_block_view() {

  global $user;
	$current_user = $user->uid;

  $query_pm = db_select('pm_index','pi');
  $query_pm->fields('pi',array('mid','is_new','deleted'));
  $query_pm->join('pm_message','pmsg','pmsg.mid = pi.mid');
  $query_pm->join('users','u','u.uid = pmsg.author');
  $query_pm->fields('u',array('name'));
  $query_pm->condition('recipient',$current_user,'=');
  $query_pm->condition('deleted',0,'=');
  $query_pm->orderBy('timestamp', 'DESC');
  $query_pm->range(0,2);
  $query = $query_pm->execute()
  ->fetchAll();

  $no_result = count($query);
  $output = '<div class = "pm-custom">';

  if ($no_result != 0) {
		foreach($query as $res) {
			$msg_id = $res->mid;
      $deleted = $res->deleted;
			$author = $res->name;

			$result = db_select('pm_message','pm')
			->fields('pm',array('subject','timestamp'))
			->condition('mid',$msg_id,'=')
			->execute()
			->fetchAssoc();

      $pm_new = $res->is_new.'<br/>';
      if($pm_new == 1){
        $new = '<div class = "pm-new">'.'NEW! '.'</div>';
      }

      $output .= '<div class="pm">'.'<div class = "pm-subject"><a href = '.'../messages/view/'.$msg_id.'>'.$new.$pm_subject = $result['subject'].'</a></div>'.'<div class = "pm-admin">'.$author.'</div>'.'<div class = "pm-date">'.$pm_date = date('F d, Y',$result['timestamp']).'</div>'.'</div>';
		}
    return $output.'<a class="pm-view" href="../messages">View All Messages</a>'.'</div>';
  } else {
    return 'No Messages to display';
  }
}

/**
 * Function callback for homepage booklist slider.
 */
function homepage_slider(){

	$output .= '<ul class="booklist-pager"><input type="radio" name="colorRadio" id="r1" value="blslider1" checked><label for="r1"></label><input type="radio" name="colorRadio" id="r2" value="blslider2"><label for="r2"></label><input type="radio" name="colorRadio" id="r3" value="blslider3"><label for="r3"></label></ul>';
	$block = module_invoke('views', 'block_view', 'booklist_slideshow-block_2');
	$output .= '<div class="blslider1 slide">'. render($block['content']). '</div>';

	$block = module_invoke('views', 'block_view', 'booklist_slideshow-block_3');
	$output .= '<div class="blslider2 slide">'. render($block['content']). '</div>';

	$block = module_invoke('views', 'block_view', 'booklist_slideshow-block_4');
	$output .= '<div class="blslider3 slide">'. render($block['content']). '</div>';

	return $output;
}

/**
 * Function callback for header menu for mobile
 */
function header_menu_mobile(){

	$output .= '<div class = "mobile_menu">';

	$block = module_invoke('views', 'block_view', 'top_block-block_2');
	$output .= render($block['content']);

	$block = module_invoke('menu', 'block_view', 'menu-secoundary-menu-mobile');
	$output .= render($block['content']).'</div>';

	return $output;
}