<?php

/**
 * Implementation of hook_menu()
 */

function private_msg_custom_menu() {
  $items['my_reviews'] = array(
    'title' => 'Reviews',
    'page callback' => 'user_reviews',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['my_booklist'] = array(
    'title' => 'Booklist',
    'page callback' => 'user_booklist',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  return $items;
}


function private_msg_custom_form_alter(&$form, &$form_state, $form_id) {
	// echo '<pre>'; print_r($form_id);die();
}

function user_reviews(){
	return '';
}

function user_booklist(){
  return '';
}
/**
 * Implements hook_block_info().
 */
function private_msg_custom_block_info() {
  $blocks = array();
  $blocks['pm_block'] = array(
    'info' => t('Private Message Dashboard Block'),
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function private_msg_custom_block_view($delta='') {
  $block = array();
  
  switch($delta) {
    case 'pm_block' :
      $block['content'] = pm_block_view();
      break;
  }
  
  return $block;
}

function pm_block_view(){

  global $user;
	$current_user = $user->uid;

  $query_pm = db_select('pm_index','pi');
  $query_pm->fields('pi',array('mid','is_new','deleted'));
  $query_pm->join('pm_message','pmsg','pmsg.mid = pi.mid');
  $query_pm->join('users','u','u.uid = pmsg.author');
  $query_pm->fields('u',array('name'));
  $query_pm->condition('recipient',$current_user,'=');
  $query_pm->condition('deleted',0,'=');
  $query_pm->orderBy('timestamp', 'DESC');
  $query_pm->range(0,2);
  $query = $query_pm->execute()
  ->fetchAll();

  $no_result = $query[0];

  $output = '<div class = "pm-custom">';

if(isset($no_result)){

	foreach($query as $res){
	$msg_id = $res->mid;
  $deleted = $res->deleted;
	$author = $res->name;

	 $result = db_select('pm_message','pm')
	 ->fields('pm',array('subject','timestamp'))
	 ->condition('mid',$msg_id,'=')
	 ->execute()
	 ->fetchAssoc();

   $pm_new = $res->is_new.'<br/>';
  if($pm_new == 1){
  	$new = '<div class = "pm-new">'.'NEW! '.'</div>';
  }
	$output .= '<div class="pm">'.'<div class = "pm-subject">'.$new.$pm_subject = $result['subject'].'</div>'.'<div class = "pm-admin">'.$author.'</div>'.'<div class = "pm-date">'.$pm_date = date('F d, Y',$result['timestamp']).'</div>'.'</div>';
	
	}
	return $output.'<a class="pm-view" href="../messages">View All Messages</a>'.'</div>';
  }else{
    return 'No Messages to display';
  }
}