<?php

/**
 * @file
 * Install, update and uninstall functions for the random list widget module.
 */

/**
 * Implements hook_field_schema().
 */
//function list_field_schema($field) {
//  return array(
//    'columns' => array(
//      'value' => array(
//        'type' => 'varchar',
//        'length' => 255,
//        'not null' => FALSE,
//      ),
//    ),
//    'indexes' => array(
//      'value' => array('value'),
//    ),
//  );
//}
