<?php

/**
 * This is a script to import from D6 to D7
 */

/**
 * Implements hook_flush_caches().
 */
function librarysite_migrate_d6tod7_flush_caches() {
  librarysite_migrate_d6tod7_register_migrations();
}

/**
 * Register all D6->D7 migrations.
 */
function librarysite_migrate_d6tod7_register_migrations() {
  /**
   * Each migration being registered takes an array of arguments, some required
   * and some optional. Start with the common arguments required by all - the
   * source_connection (connection key, set up in settings.php, pointing to
   * the Drupal 6 database) and source_version (major version of Drupal).
   */
  $common_arguments = array(
    'source_connection' => 'legacy',
    'source_version' => 6,
    'format_mappings' => array(
                   '1' => 'filtered_html', // Filtered HTML
                   '2' => 'filtered_html', // PHP code
                   '3' => 'filtered_html', // Full HTML
                   ),           
  );

  // The description and the migration machine name are also required arguments,
  // which will be unique for each migration you register.
  $arguments = $common_arguments + array(
    'description' => t('Migration of users from Drupal 6'),
    'machine_name' => 'User',
  );
  
  $role_arguments = $common_arguments + array(
    'machine_name' => 'ExampleRole',
    'description' => t('Import Drupal 6 roles'),
    'role_mappings' => array(
      'site admin' => 'administrator',
      'manager' => 'librarian',
    ),
  );
  

  // We just use the migrate_d2d D6 migration class as-is.
  Migration::registerMigration('DrupalUser6Migration', $arguments['machine_name'],
                               $arguments);

  // For vocabulary migrations, source_vocabulary and destination_vocabulary are
  // required arguments. Note that in Drupal 6 vocabularies did not have machine
  // names, so we use the vocabulary ID to uniquely identify them.
  $vocabulary_arguments = array(
    array(
      'description' => t('Migration of Topics terms from Drupal 6'),
      'machine_name' => 'Topics',
      'source_vocabulary' => '3',  // D6 Vocabulary ID
      'destination_vocabulary' => 'tags',
    ),
    array(
      'description' => t('Migration of Blog Section terms from Drupal 6'),
      'machine_name' => 'BlogSection',
      'source_vocabulary' => '2',  // D6 Vocabulary ID
      'destination_vocabulary' => 'blog_section',
    ),
  );

  // Again, we're using the migrate_d2d class directly.
  // The soft dependency says that while we don't have to run the user migration
  // first, we want to make sure it's listed first so the vocubularies are
  // listed right ahead of the node migrations.
  $common_vocabulary_arguments = $common_arguments + array(
    'class_name' => 'DrupalTerm6Migration',
    'soft_dependencies' => array('User'),
  );
  foreach ($vocabulary_arguments as $arguments) {
    $arguments += $common_vocabulary_arguments;
    Migration::registerMigration($arguments['class_name'], $arguments['machine_name'],
                                 $arguments);
  }

  // Node migrations - each has its own class derived from the migrate_d2d class,
  // specifying its particular field mappings and transformations. source_type
  // and destination_type are required arguments.
  $node_arguments = array(
    array(
      'class_name' => 'PageMigration',
      'description' => t('Migration of page nodes from Drupal 6'),
      'machine_name' => 'Page',
      'source_type' => 'page',
      'destination_type' => 'page',
    ),
    array(
      'class_name' => 'EventMigration',
      'description' => t('Migration of event nodes from Drupal 6'),
      'machine_name' => 'Event',
      'source_type' => 'event',
      'destination_type' => 'event',
    ),
    array(
      'class_name' => 'BranchMigration',
      'description' => t('Migration of branch nodes from Drupal 6'),
      'machine_name' => 'Branch',
      'source_type' => 'branch',
      'destination_type' => 'branch',
    ),
    array(
      'class_name' => 'CheckitoutMigration',
      'description' => t('Migration of check it out nodes from Drupal 6'),
      'machine_name' => 'Checkitout',
      'source_type' => 'story',
      'destination_type' => 'article',
    ),
    array(
      'class_name' => 'FaqMigration',
      'description' => t('Migration of faq nodes from Drupal 6'),
      'machine_name' => 'FAQ',
      'source_type' => 'faq',
      'destination_type' => 'faq',
    ),

  );
  // Tell the node migrations where the users are coming from, so they can
  // set up the dependency and resolve D6->D7 uids.
  $common_node_arguments = $common_arguments + array(
    'user_migration' => 'User',
  );
  foreach ($node_arguments as $arguments) {
    $arguments = array_merge_recursive($arguments, $common_node_arguments);
    Migration::registerMigration($arguments['class_name'], $arguments['machine_name'],
                                 $arguments);
  }

  // Menu migrations -- same requirements as users
  $menu_arguments = $common_arguments + array(
    'description' => t('Migration of menus from Drupal 6'),
    'machine_name' => 'Menu',
  );

  // We just use the migrate_d2d D6 migration class as-is.
  Migration::registerMigration('DrupalMenu6Migration', $menu_arguments['machine_name'],
                               $menu_arguments);

  // Menu links migrations -- basic requirements, plus must set up menu dependency
  $menu_links_arguments = $common_arguments + array(
    'description' => t('Migration of menu links from Drupal 6'),
    'machine_name' => 'MenuLinks',
    'menu_migration' => $menu_arguments['machine_name'],
  );
  Migration::registerMigration('DrupalMenuLinks6Migration', $menu_links_arguments['machine_name'],
                               $menu_links_arguments);
}

/**
 * Implements hook_migrate_api().
 */
function librarysite_migrate_d6tod7_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}
