<?php

/**
 * Implement hook_menu(); for leaderboard page.
 */

function play_library_teens_leaderboard_menu() {
  $items['leaderboard'] = array(
    'title' => 'Leaderboard',
    'page callback' => 'pl_leaderboard_page',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  return $items;
}


function pl_leaderboard_page() {
  $imgStyle = 'avatar_style';
   $activity = pl_activities_view_select_option();
   $activity_id = array();
   foreach ($activity as $key => $value) {
     $activity_id[] = $key;
   }

   
     $query = db_select('eck_activity', 'eck_act');
     $query->join('field_data_field_activity_entry_activity', 'act_entry', 'act_entry.entity_id = eck_act.id');
     $query->join('users', 'u', 'u.uid = eck_act.uid');
    $query->condition('act_entry.field_activity_entry_activity_target_id', $activity_id, 'IN');
    $query->condition('act_entry.bundle', 'activity_entry', '=');
    $query->condition('eck_act.type', 'activity_entry', '=');
    $query->fields('act_entry', array('field_activity_entry_activity_target_id'));
    $query->addExpression('COUNT(act_entry.field_activity_entry_activity_target_id)', 'label');
    $query->fields('eck_act', array('uid'));
    $query->fields('u', array('name'));
    $query->groupBy('eck_act.uid');
    $result = $query->execute()->fetchAll();
    $out ='';
    $out .= '<div><ol>';
    foreach ($result as $key => $value) {
      $name = $value->name;
      $no_stamp = $value->label;
      $user_uid = $value->uid;
      $avatar = pl_user_avatar_progress_page($user_uid, $imgStyle);
      
      $out .= '<li><span>'.$avatar.'</span><span>'. $no_stamp. '</span></li>';

      
    }

    $out .= '</ol></div>';

    return $out;
   
} 



/**
 * Implements hook_block_info().
 */
function play_library_teens_leaderboard_block_info() {

  $blocks = array();

  $blocks['leaderboard_block'] = array(
    'info' => t('Leader Board block for teens dashboard'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function play_library_teens_leaderboard_block_view($delta = '') {
  $block = array();
  
  switch($delta) {
    case 'leaderboard_block' :
      $block['subject'] = '';
      $block['content'] = leader_board_teens_dashboard();
      break;
  }
  
  return $block;
}


/**
 *  Leaderboard block function.
 */

function leader_board_teens_dashboard() {
  $imgStyle = 'avatar_style';
   $activity = pl_activities_view_select_option();
   $activity_id = array();
   foreach ($activity as $key => $value) {
     $activity_id[] = $key;
   }

   
     $query = db_select('eck_activity', 'eck_act');
     $query->join('field_data_field_activity_entry_activity', 'act_entry', 'act_entry.entity_id = eck_act.id');
     $query->join('users', 'u', 'u.uid = eck_act.uid');
    $query->condition('act_entry.field_activity_entry_activity_target_id', $activity_id, 'IN');
    $query->condition('act_entry.bundle', 'activity_entry', '=');
    $query->condition('eck_act.type', 'activity_entry', '=');
    $query->fields('act_entry', array('field_activity_entry_activity_target_id'));
    $query->addExpression('COUNT(act_entry.field_activity_entry_activity_target_id)', 'label');
    $query->fields('eck_act', array('uid'));
    $query->fields('u', array('name'));
    $query->groupBy('eck_act.uid');
    $query->range(0, 5);
    $result = $query->execute()->fetchAll();
    $out ='';
    $out .= '<div><ol>';
    foreach ($result as $key => $value) {
      $name = $value->name;
      $no_stamp = $value->label;
      $user_uid = $value->uid;
      $avatar = pl_user_avatar_progress_page($user_uid, $imgStyle);
      
      $out .= '<li><span>'.$avatar.'</span><span>'. $no_stamp. '</span></li>';

      
    }
    $out .= '<span><a href="leaderboard">More</a></span>';

    $out .= '</ol></div>';

    return $out;

}
