
<?php

/**
 * returns user name and user avatar with public profile link.
 */
function pl_user_avatar_user_name($uid){

  if($uid == ''){
    return FALSE;
  }

  global $user;
  $user_pf = profile2_load_by_user($uid);
  $user_main = user_load($uid);

  $img_id = $user_pf['main']->field_user_avatar[LANGUAGE_NONE][0]['target_id'];
  $user_name = $user_main->name;

  $query = db_select('field_data_field_avatar_image', 't');
  $query->join('file_managed', 'n', 'n.fid = t.field_avatar_image_fid');
  $result = $query
    ->fields('n', array('uri'))
    ->condition('t.entity_id', $img_id)
    ->execute();

  $img_uri_query = $result->fetchObject();
  $img_uri = $img_uri_query->uri;
  $img_path = file_create_url($img_uri);
  if($img_path){
    $img = "<img src='$img_path'>";
    return $img.'<a href ="/users/public_profile/'.$uid.'">'.$user_name.'</a>';
  } else{
    return FALSE;
  }
}

/**
 * Implement hook_menu(); for leaderboard page.
 */

function play_library_teens_leaderboard_menu() {
  $items['leaderboard'] = array(
    'title' => 'Leaderboard',
    'page callback' => 'pl_leaderboard_page',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  return $items;
}


function pl_leaderboard_page() {
  if (module_exists('play_progress_teen')){
   $activity = pl_activities_view_select_option();
   $activity_id = array();
   foreach ($activity as $key => $value) {
     $activity_id[] = $key;
   }
  }
  else{
    //Get all activity ids with firing hook progress_page
    $act_que = db_select('field_data_field_activity_fired_hook', 'firhook');
    $act_que-> condition('firhook.field_activity_fired_hook_value', 'progress_page');
    $act_que->fields('firhook', array('entity_id'));
    $activity_ids = $act_que->execute()->fetchAll();

    foreach ($activity_ids as $key => $value) {
      $activity_id[] = $value->entity_id;
    }
  }

   
     $query = db_select('eck_activity', 'eck_act');
     $query->join('field_data_field_activity_entry_activity', 'act_entry', 'act_entry.entity_id = eck_act.id');
     $query->join('users', 'u', 'u.uid = eck_act.uid');
    $query->condition('act_entry.field_activity_entry_activity_target_id', $activity_id, 'IN');
    $query->condition('act_entry.bundle', 'activity_entry', '=');
    $query->condition('eck_act.type', 'activity_entry', '=');
    $query->condition('u.uid', 0, '!=');
    $query->fields('act_entry', array('field_activity_entry_activity_target_id'));
    $query->addExpression('COUNT(act_entry.field_activity_entry_activity_target_id)', 'label');
    $query->fields('eck_act', array('uid'));
    $query->fields('u', array('name'));
    $query->groupBy('eck_act.uid');
    $query->orderBy('label', 'DESC');
    $result = $query->execute()->fetchAll();
    $out ='';
    $out .= '<div><ol>';
    foreach ($result as $key => $value) {

      $name = $value->name;
      $no_stamp = $value->label;
      $user_uid = $value->uid;
      $avatar = pl_user_avatar_user_name($user_uid);
      
      $out .= '<li><span>'.$avatar.'</span><span>'. $no_stamp. ' '. 'stamps</span></li>';

      
    }
   
    $out .= '</ol></div>';

    return $out;
   
} 



/**
 * Implements hook_block_info().
 */
function play_library_teens_leaderboard_block_info() {

  $blocks = array();

  $blocks['leaderboard_block'] = array(
    'info' => t('Leaderboard'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function play_library_teens_leaderboard_block_view($delta = '') {
  $block = array();
  
  switch($delta) {
    case 'leaderboard_block' :
      $block['subject'] = '';
      $block['content'] = leader_board_teens_dashboard();
      break;
  }
  
  return $block;
}


/**
 *  Leaderboard block function.
 */

function leader_board_teens_dashboard() {
  if (module_exists('play_progress_teen')){
   $activity = pl_activities_view_select_option();
   $activity_id = array();
   foreach ($activity as $key => $value) {
     $activity_id[] = $key;
   }
  }
  else{
    //Get all activity ids with firing hook progress_page
    $act_que = db_select('field_data_field_activity_fired_hook', 'firhook');
    $act_que-> condition('firhook.field_activity_fired_hook_value', 'progress_page');
    $act_que->fields('firhook', array('entity_id'));
    $activity_ids = $act_que->execute()->fetchAll();

    foreach ($activity_ids as $key => $value) {
      $activity_id[] = $value->entity_id;
    }
  }

   
     $query = db_select('eck_activity', 'eck_act');
     $query->join('field_data_field_activity_entry_activity', 'act_entry', 'act_entry.entity_id = eck_act.id');
     $query->join('users', 'u', 'u.uid = eck_act.uid');
    $query->condition('act_entry.field_activity_entry_activity_target_id', $activity_id, 'IN');
    $query->condition('act_entry.bundle', 'activity_entry', '=');
    $query->condition('eck_act.type', 'activity_entry', '=');
    $query->fields('act_entry', array('field_activity_entry_activity_target_id'));
    $query->addExpression('COUNT(act_entry.field_activity_entry_activity_target_id)', 'label');
    $query->fields('eck_act', array('uid'));
    $query->fields('u', array('name'));
    $query->groupBy('eck_act.uid');
    $query->orderBy('label', 'DESC');
    $query->range(0, 5);
    $result = $query->execute()->fetchAll();
    $out ='';
    $out .= '<div><ol>';
    foreach ($result as $key => $value) {
      $name = $value->name;
      $no_stamp = $value->label;
      $user_uid = $value->uid;
      $avatar = pl_user_avatar_user_name($user_uid);
      
      $out .= '<li><span>'.$avatar.'</span><span>'. $no_stamp. 'stamps</span></li>';

      
    }
    $out .= '<span><a href="/leaderboard">More</a></span>';

    $out .= '</ol></div>';

    return $out;

}
